---
version: '3.2'

services:
    app:
        build:
            context: .docker
            dockerfile: Dockerfile
        environment:
            TZ: Asia/Tokyo
            API_TOKEN: YOUR_API_TOKEN
            ROOM_ID: YOUR_ROOM_ID

        volumes:
        - ".:/app"
        - "node_modules:/app/node_modules"

volumes:
    node_modules:
